### PR TITLE
docs(notebooks): add utility scaling demo

### PR DESCRIPTION
**Pull request by pedrorrivero**
### Summary
Adds Utility Scaling demo notebook cleaned and updated to Qiskit 1.0.

### Details and comments
Requires merging of the following PRs first:
- [x] #14 
- [x] #15 
- [x] ~#16~
- [x] #17 

All code plus notebook can be found in the [`scaling`](https://github.com/IBM-Quantum-Technical-Enablement/quantum-enablement/tree/scaling) branch of this repository for ease of access and execution. This is the way it has been shared since it was ready with people that required early access (e.g. for preparation of Practitioner's Forum APAC).

This PR is meant to provide a place to review the notebook in isolation.

### CODE REVIEW

**Comment by pedrorrivero** [comment]
Tests seem to fail due to the name of the file holding the cached results being invalid for _Windows_:
```
> Run actions/checkout@v3
Syncing repository: IBM-Quantum-Technical-Enablement/quantum-enablement
> Getting Git version info
Temporarily overriding HOME='D:\a\_temp\e528dd69-442a-4685-be32-65faa8c21fe5' before making global git config changes
Adding repository directory to the temporary git global config as a safe directory
"C:\Program Files\Git\bin\git.exe" config --global --add safe.directory D:\a\quantum-enablement\quantum-enablement
Deleting the contents of 'D:\a\quantum-enablement\quantum-enablement'
> Initializing the repository
> Disabling automatic garbage collection
> Setting up auth
> Fetching the repository
> Determining the checkout info
v Checking out the ref
  "C:\Program Files\Git\bin\git.exe" checkout --progress --force refs/remotes/pull/20/merge
  Error: error: invalid path 'docs/notebooks/scaling/12x12_2024-02-16T18:40:[14](https://github.com/IBM-Quantum-Technical-Enablement/quantum-enablement/actions/runs/8084536689/job/22090468670?pr=20#step:2:15).0352[19](https://github.com/IBM-Quantum-Technical-Enablement/quantum-enablement/actions/runs/8084536689/job/22090468670?pr=20#step:2:21)+00:00.json'
  Error: The process 'C:\Program Files\Git\bin\git.exe' failed with exit code 128
```

**Comment by itoko** [comment]
I've just found `average_distributions` function should handle the edge case where the counts of all-zero state is 0. Current notebook sometimes fails with `ValueError` when plotting the "Readout probabilities at different noise levels" figure. Example of half-baked figure looks like below (xval label 1024 suggests all-zero state is not observed within the shots).
```
ValueError: The number of FixedLocator locations (3), usually from a call to set_ticks, does not match the number of labels (2).
```
image

**Comment by itoko** [comment]
Another small comment is `datetime.UTC` seems not in Python 3.10. If we need to support 3.10 or earlier, we many need to use `datetime.timezone.utc` instead.

**Comment by pedrorrivero** [comment]
Thanks for the comments @itoko 🙇🏼‍♂️ 

Although we have chatted already I will include my responses here for transparency.

The `ValueError` that you report is merely for plotting, the rest of the notebook should run smoothly nonetheless. This code should be able to fix it thought:
```python
from qiskit.visualization import plot_distribution
from copy import deepcopy
import matplotlib.pyplot as plt

plt.rcParams.update({"text.usetex": True, "font.family": "Helvetica"})
fig, ax = plt.subplots(dpi=200)

ACCURATE_READOUT = "0" * NUM_QUBITS
plots_dict = deepcopy(results_dict)
plots_dict = {
    nf: {"0": counts.pop(ACCURATE_READOUT), "1": sum(counts.values())}
    for nf, counts in plots_dict.items()
}

plot_distribution(
    [plots_dict.get(nf) for nf in NOISE_FACTORS], 
    legend=[f"Noise factor: {nf:.1f}" for nf in NOISE_FACTORS],
    color=['lightgray', 'gray', 'black'],
    title="Readout probabilities at different noise levels",
    number_to_keep=1,
    ax=ax,
)
ax.set_xticklabels(['Accurate', 'Error'], rotation=0)
ax.legend(fontsize=11)

plt.show()
```

**Comment by itoko** [comment]
We need to change the file name `12x12_2024-03-12T21:18:13.498254+00:00.json` not to use ":" in it for Windows users. Otherwise, windows users cannot install `quantum-enablement` module, i.e. they are not able to do `pip install quantum-enablement@git+https://github.com/IBM-Quantum-Technical-Enablement/quantum-enablement`. I heard it today from a windows user.

**Comment by pedrorrivero** [comment]
All requests and pending PRs have been addressed. Marking this as ready for review now.

**Review by miamico — CHANGES_REQUESTED** [review]
I'm unable to comment this notebook line by line (source code is not viewable online), so I'll give my review in this comment:

1. "To this end, we will begin studying conceptually different hardware-native quantum circuits, that will turn out equivalent in practice"
There is a caveat here which explains why the different circuits which you consider all turn out to give similar circuit structure: i) MBL and TFIM dynamics are both Hamiltonian simulation tasks and QAOA again relies on time-evolution generated by the problem Hamiltonian so not that different from a Hamiltonian simulation task. ii) In all circuits you have assumed the same topology, Hamiltonian with nearest neighbor interaction for qubits on a line. 
For these reasons the circuits end up all looking similar to each other. So instead of claiming this is a generic structure for quantum circuits, you could say that Hamiltonian simulation task is widely used in quantum computing.

2. "Then we will introduce a derivative form of the above circuits in order to address result validation: compute-uncompute."
Let's not introduce new terminology (or reference it if use it elsewhere). Circuit constructed by appending $U^{\dag}$ to $U$ are commonly known as `mirror circuits`. Let's use this terminology which is already in use in the community.

3. "[Twirling](https://www.zlatko-minev.com/blog/twirling) or randomized compiling is a well known and widely used technique for converting arbitrary noise channels into Pauli channels (e.g. depolarizing noise)."
This is incorrect. Twirling is a technique to taylor the noise. Depending on the gates used in the twirling bases, you may end up with Pauli noise (or not). See this reference for a comprehensive and straightforward introduction to twirling: https://glassnotes.github.io/OliviaDiMatteo-Unitary2Designs.pdf

4. "Unfortunately, idle qubits decohere more easily than those on which operations are being applied. "
This statement is also not generally correct. In fact, there is plenty of research showing that T2 is smaller for driven qubits than the one measured when they are idle. The actual problem is that the qubits in our device are always coupled to each other and the crosstalks effect induced by this coupling can induce coherent errors on the idling qubits when circuits with more than 2 qubits are considered.

5. "single-qubit measurement obfuscation matrices"
I never heard this term, shouldn't this be confusion matrices (for example https://mitiq.readthedocs.io/en/stable/guide/rem.html)

**Review by miamico — APPROVED** [review]
Awesome, looks great to me now! :D

**Pull request merged**
